[package]
name = "casper-engine-test-support"
version = "2.0.0" # when updating, also update 'html_root_url' in lib.rs
authors = ["Fraser Hutchison <fraser@casperlabs.io>"]
edition = "2018"
description = "Library to support testing of Wasm smart contracts for use on the Casper network."
documentation = "https://docs.rs/casper-engine-test-support"
readme = "README.md"
homepage = "https://casperlabs.io"
repository = "https://github.com/casper-ecosystem/casper-engine-test-support"
license = "Apache-2.0"

[dependencies]
casper-contract = { version = "1.4.1", default-features = false }
casper-execution-engine = { version = "1.4.1", features = ["gens"] }
casper-types = "1.4.1"
casper-hashing = "1.4.1"
lmdb = "0.8.0"
log = "0.4.8"
num-rational = "0.4.0"
num-traits = "0.2.10"
once_cell = "1.5.2"
rand = "0.8.3"

[dev-dependencies]
version-sync = "0.9.3"

[features]
use-as-wasm = []
test-support = ["casper-contract/test-support"]
